### ISSUE TITLE
Having trouble building (Windows)

### ISSUE THREAD

**Issue by pixelmike** [jiborobot/pixi-animate-extension#40]
Followed the build instructions, and got as far as `Starting 'package'` and then errored out because it could not connect to `https://timestamp.geotrust.com/tsa`.

Is it possible to download a pre-built zxp file from somewhere? We're just looking to export animations from Adobe Animate and load them in a pixi.js app. Not sure what the best approach to getting the plugin installed is.

Here is the log:

```
$ gulp --plugin --install
[14:55:18] Using gulpfile C:\webdev\AdobeExt\pixi-animate-extension\gulpfile.js
[14:55:18] Starting 'default'...
[14:55:18] +-------------------+
[14:55:18] |    PixiAnimate    |
[14:55:18] +-------------------+
[14:55:18] Mode:  Release
[14:55:18] Starting 'plugin'...
[14:55:18] Starting 'plugin-win-debug'...
[14:56:35] MSBuild complete!
[14:56:35] Finished 'plugin-win-debug' after 1.28 min
[14:56:35] Starting 'plugin-win'...
[14:57:57] MSBuild complete!
[14:57:57] Finished 'plugin-win' after 1.35 min
[14:57:57] Finished 'plugin' after 2.65 min
[14:57:57] Starting 'clean'...
[14:57:57] Finished 'clean' after 4.07 ms
[14:57:57] Starting 'lint'...
[14:57:58] Finished 'lint' after 1.12 s
[14:57:58] Starting 'stage'...
[14:57:58] Finished 'stage' after 71 ms
[14:57:58] Starting 'build-publish'...
[14:58:02] Finished 'build-publish' after 4.18 s
[14:58:02] Starting 'build-dialog'...
[14:58:02] Finished 'build-dialog' after 70 ms
[14:58:02] Starting 'build-preview-app'...
[14:58:05] Finished 'build-preview-app' after 2.93 s
[14:58:05] Starting 'build-preview'...
[14:58:05] Finished 'build-preview' after 30 ms
[14:58:05] Starting 'build-spritesheets'...
[14:58:05] Finished 'build-spritesheets' after 117 ms
[14:58:05] Starting 'runtime-copy'...
[14:58:05] Finished 'runtime-copy' after 8.34 ms
[14:58:05] Starting 'runtime-copy-debug'...
[14:58:05] Finished 'runtime-copy-debug' after 17 ms
[14:58:05] Starting 'plugin-copy-mac'...
[14:58:05] Finished 'plugin-copy-mac' after 5.79 ms
[14:58:05] Starting 'plugin-copy-win'...
[14:58:05] Finished 'plugin-copy-win' after 20 ms
[14:58:05] Starting 'package'...
Error - cannot contact the chosen TSA. Please make sure the URL is valid and that you are connected to the internet.
[14:58:27] 'package' errored after 21 s
[14:58:27] Error: Command `.\build\bin\ZXPSignCmd.exe -sign "com.jibo.PixiAnimate" "PixiAnimate.zxp" "build/certificate.p12" "password" -tsa "https://timestamp.geotrust.com/tsa"` failed with exit code 36
    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
[14:58:27] 'default' errored after 3.15 min
[14:58:27] Error: Command `.\build\bin\ZXPSignCmd.exe -sign "com.jibo.PixiAnimate" "PixiAnimate.zxp" "build/certificate.p12" "password" -tsa "https://timestamp.geotrust.com/tsa"` failed with exit code 36
    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:897:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
```

**Comment by bigtimebuddy** [comment]
You can download the ZXP from the releases section or with [Adobe Add-ons](https://exchange.adobe.com/addons/products/14345).

**Comment by pixelmike** [comment]
Ah! Thanks very much!!
